// React
import React, { useEffect } from 'react'
// Next
import Head from 'next/head'
import { useRouter } from 'next/router'
import { GetServerSideProps, GetServerSidePropsContext } from 'next'
// Providers
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
// Utils
import { parseCookies } from '@utils/parseCookies'
// Models
import { Permissions } from '@models/auth/permission.model'
// Components
import { Layout } from '@components/shared/layout'

export const getServerSideProps: GetServerSideProps = async (
  ctx: GetServerSidePropsContext
) => {
  let cookie
  try {
    cookie = parseCookies(ctx)
    return {
      props: {
        user: cookie.user,
        permissions: cookie.permissions,
        ...(await serverSideTranslations(ctx.locale as string, [
          'menu',
          'common'
        ]))
      }
    }
  } catch (error) {
    return {
      props: {
        user: cookie && cookie.user ? cookie.user : '',
        permissions: cookie && cookie.permissions ? cookie.permissions : {}
      }
    }
  }
}

const Home = ({
  user,
  permissions
}: {
  user: string
  permissions: Permissions
}): React.ReactElement => {
  const router = useRouter()
  const { t } = useTranslation('common')

  useEffect(() => {
    if (!user) {
      router.push('/auth/login')
    }
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && (
        <Layout permissions={permissions}>
          <main>
            <h1>{t('title')}</h1>
            <div>Welcome {user}</div>
          </main>
        </Layout>
      )}
    </>
  )
}

export default Home
