// React
import React, { useEffect } from 'react'
// Next
import Head from 'next/head'
import { useRouter } from 'next/router'
import { GetServerSideProps, GetServerSidePropsContext } from 'next'
// Utils
import { parseCookies } from '@utils/parseCookies'
// Models
import { Permissions } from '@models/auth/permission.model'
import { Cookie } from '@models/auth/cookie.model'
// Components
import { Layout } from '@components/shared/layout'

export const getServerSideProps: GetServerSideProps = async (
  ctx: GetServerSidePropsContext
) => {
  let cookie: Cookie
  try {
    cookie = parseCookies(ctx)
    return {
      props: {
        user: cookie.user,
        permissions: cookie.permissions
      }
    }
  } catch (error) {
    return {
      props: {
        user: '',
        permissions: {}
      }
    }
  }
}

const Home = ({
  user,
  permissions
}: {
  user: string
  permissions: Permissions
}): React.ReactElement => {
  const router = useRouter()

  useEffect(() => {
    if (!user) {
      router.push('/auth/login')
    }
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && (
        <Layout permissions={permissions}>
          <main>
            <div>Welcome {user}</div>
          </main>
        </Layout>
      )}
    </>
  )
}

export default Home
